#! /bin/sh
# postinst script for sml-mode
set -e

## Remove obsolete debconf questions.
if dpkg --compare-versions 3.9.5-9 le-nl "$2"; then

    # Source debconf library, if present.
    if [ -e /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule    
        ## Remove all questions in the debconf database.
        db_purge
    fi

fi

#DEBHELPER#
exit 0
