#! /bin/sh
# prerm script for sml-mode.

set -e

case "$1" in
    remove|upgrade|deconfigure)
	# Remove the start-up file.  There is at most one such file.
	SITESTARTFILE=`echo /etc/emacs/site-start.d/??sml-mode.el`
	if [ -e $SITESTARTFILE ]; then 
	    rm -f $SITESTARTFILE
	fi
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#

exit 0


